### ISSUE TITLE
Error with Completion Exception from No Sleep

### ISSUE THREAD

**Issue by suerion** [jodeks-datapacks/Sleep#7]
### Describe the bug

Hey, i got some issues on my side with completionException:
Fabric 1.21.1 on 0.16.5
```
[15:29:01] [main/ERROR]: Failed to load function sleep:uninstall
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Whilst parsing command on line 11: Expected whitespace to end one argument, but found trailing data at position 16: ...le players<--[HERE]
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
        at MC/net.minecraft.resource.ProfiledResourceReload.method_18357(ProfiledResourceReload.java:35) ~[server-intermediary.jar:?]
        at MC/net.minecraft.resource.SimpleResourceReload.method_18371(SimpleResourceReload.java:62) ~[server-intermediary.jar:?]
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Whilst parsing command on line 11: Expected whitespace to end one argument, but found trailing data at position 16: ...le players<--[HERE]
        at MC/net.minecraft.server.function.CommandFunction.create(CommandFunction.java:80) ~[server-intermediary.jar:?]
        at MC/net.minecraft.server.function.FunctionLoader.method_29451(FunctionLoader.java:89) ~[server-intermediary.jar:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 8 more
[15:29:01] [main/ERROR]: Failed to load function sleep:load
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Whilst parsing command on line 13: Expected whitespace to end one argument, but found trailing data at position 16: ...le players<--[HERE]
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
        at MC/net.minecraft.resource.ProfiledResourceReload.method_18357(ProfiledResourceReload.java:35) ~[server-intermediary.jar:?]
        at MC/net.minecraft.resource.SimpleResourceReload.method_18371(SimpleResourceReload.java:62) ~[server-intermediary.jar:?]
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Whilst parsing command on line 13: Expected whitespace to end one argument, but found trailing data at position 16: ...le players<--[HERE]
        at MC/net.minecraft.server.function.CommandFunction.create(CommandFunction.java:80) ~[server-intermediary.jar:?]
        at MC/net.minecraft.server.function.FunctionLoader.method_29451(FunctionLoader.java:89) ~[server-intermediary.jar:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 8 more
[15:29:01] [main/ERROR]: Couldn't load tag minecraft:load as it is missing following references: sleep:load (from mr_sleep), cavernous:init (from file/carnourvos.zip)
```

### Steps to reproduce

Hugh Modpack Server Log:
https://mclo.gs/iKlXez6

### Expected behavior

Commands should work fine.

**Comment by Jodekq** [comment]
Is the datapack enabled? + if you do /reload, is there a message like "Sleep loaded" in the chat?

**Comment by suerion** [comment]
> Is the datapack enabled? + if you do /reload, is there a message like "Sleep loaded" in the chat?

will look

**Comment by suerion** [comment]
Oh no, server crash on reload, because of watchdog, could not say it yet, if it does load, need do debug first the error with Watchdog

**Comment by suerion** [comment]
@Jodekq had found an issue -> had created an new Issue
